version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 15
    commit-message:
      prefix: "fix(deps)"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 15
    commit-message:
      prefix: "fix(deps)"
    groups:
      gomodules:
        patterns:
          - "*"
