cluster:
  cluster:
    initdb:
      database: app
      owner: app
    instances: 2
    storage:
      size: 10Gi
    walStorage:
      enabled: true
      size: 2Gi
    postgresql:
      synchronous:
        enabled: true
        method: any
        number: 1
