{{- $model := index .Values.model.profile .Values.model.name }}
{{- $gpu := index .Values.gpu.profile .Values.gpu.name }}
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  predictor:
    deploymentStrategy:
      type: Recreate
    runtimeClassName: nvidia
    nodeSelector:
      feature.node.kubernetes.io/pci-10de.present: "true"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    model:
      modelFormat:
        name: huggingface
      runtime: {{ .Release.Name }}-runtime
      args:
        - "--served-model-name={{ $model.servedModelName }}"
        {{- range $model.args }}
        - {{ . | quote }}
        {{- end }}
      env:
        - name: MODEL_ID
          value: {{ $model.modelId | quote }}
      resources:
        {{- toYaml $gpu.resources | nindent 8 }}
