# -----------------------------
# InferenceService (Qwen2.5-Coder 32B Instruct AWQ)
# -----------------------------
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen25-coder-32b
spec:
  predictor:
    deploymentStrategy:
      type: Recreate
    runtimeClassName: nvidia
    nodeSelector:
      feature.node.kubernetes.io/pci-10de.present: "true"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    model:
      modelFormat:
        name: huggingface
      runtime: vllm-qwen25-coder-32b-runtime
      args:
        - "--served-model-name=qwen25-coder-32b"
      env:
        - name: MODEL_ID
          value: "Qwen/Qwen2.5-Coder-32B-Instruct-AWQ"
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: "12Gi"
        requests:
          nvidia.com/gpu: 1
          memory: "12Gi"
