apiVersion: v2
type: application
name: oidc-discovery-proxy
description: Expose the Kubernetes OIDC discovery endpoints publicly for service account identity federation.
icon: https://github.com/kommodity-io.png
version: 1.0.2
appVersion: "v1.2.1"
dependencies:
  - name: oidc-discovery-proxy
    version: 1.2.1
    repository: "oci://ghcr.io/kommodity-io/charts"
