# References:
# - https://artifacthub.io/docs/topics/repositories/container-images/#repository-metadata
# - https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml
repositoryID: ""
owners:
  - name: Nicklas Frahm
    email: nicklas.frahm@gmail.com
