kserve:
  enabled: true
  kserve:
    controller:
      deploymentMode: RawDeployment
      gateway:
        ingressGateway:
          enableGatewayApi: true
          kserveGateway: platform/public-web-gateway

kserve-crd:
  enabled: true
