# -----------------------------
# InferenceService (Gemma 4 27B MoE)
# -----------------------------
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: gemma4-moe
spec:
  predictor:
    deploymentStrategy:
      type: Recreate
    runtimeClassName: nvidia
    nodeSelector:
      feature.node.kubernetes.io/pci-10de.present: "true"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    model:
      modelFormat:
        name: huggingface
      runtime: vllm-gemma4-runtime
      args:
        - "--served-model-name=gemma4-26b-a4b-it"
      env:
        - name: MODEL_ID
          value: "cyankiwi/gemma-4-26B-A4B-it-AWQ-4bit"
        # BELOW MODELS: GPU TOO SMALL FOR KV CACHE.
        # - name: MODEL_ID
        #   value: "Intel/gemma-4-31B-it-int4-AutoRound"
        # - name: MODEL_ID
        #   value: "Intel/gemma-4-26B-A4B-it-int4-mixed-AutoRound"
        - name: PROMPT_TOKEN_PRICE
          value: "0.6953"
        - name: PROMPT_CACHED_TOKEN_PRICE
          value: "0.0695"
        - name: COMPLETION_TOKEN_PRICE
          value: "3.6859"
        - name: COMPLETION_CACHED_TOKEN_PRICE
          value: "0.3686"
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: "12Gi"
        requests:
          nvidia.com/gpu: 1
          memory: "12Gi"
